# Generated by Django 4.1 on 2023-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0003_remove_newmember_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmember',
            name='education',
        ),
        migrations.AddField(
            model_name='newmember',
            name='resume',
            field=models.FileField(default=1, upload_to='resume'),
            preserve_default=False,
        ),
    ]
