# Generated by Django 4.1 on 2023-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0004_remove_newmember_education_newmember_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmember',
            name='resume',
        ),
        migrations.AddField(
            model_name='newmember',
            name='education',
            field=models.CharField(choices=[('PlusTwo', 'PlusTwo'), ('BA', 'BA'), ('Bcom', 'Bcom'), ('BBA', 'BBA'), ('MA', 'MA'), ('Mcom', 'Mcom'), ('MBA', 'MBA'), ('Diploma', 'Diploma'), ('Other', 'Other')], max_length=250, null=True),
        ),
    ]
