# Generated by Django 4.1 on 2023-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0006_remove_newmember_education_alter_newmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='education',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
