# Generated by Django 4.1 on 2023-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0007_newmember_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='jobtype',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
