# Generated by Django 4.1 on 2023-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0008_newmember_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='sity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
