# Generated by Django 4.1 on 2023-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0010_rename_sity_newmember_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
