# Generated by Django 4.1 on 2023-04-15 14:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0011_newmember_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='database',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySQL', 'MySQL'), ('Postgree', 'Postgree'), ('MongoDB', 'MongoDB'), ('FireBase', 'Firebase'), ('Oracle', 'Oracle')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newmember',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('ASP.NET Core', 'ASP.NET Core')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newmember',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Javascript', 'Javascript'), ('PHP', 'PHP')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newmember',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js'), ('Chart.js', 'Chart.js'), ('Gsap', 'Gsap')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newmember',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React native', 'React native'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Kotlin', 'Kotlin'), ('Xamarin', 'Xamarin')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newmember',
            name='other',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Git', 'Git'), ('Bootstrap', 'Bootstrap'), ('Docker', 'Docker'), ('SQL', 'SQL'), ('GraphQL', 'GraphQL')], default='', max_length=200),
        ),
    ]
