# Generated by Django 4.1 on 2023-04-16 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0013_remove_newmember_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
