# Generated by Django 4.1 on 2023-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_member', '0015_newmember_fresher_or_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='salary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
